name: Test & Build Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Jest tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ Backend, SurveyEvaluation ]
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        working-directory: ${{ matrix.service }}
        run: npm ci
      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: npm test
  docker:
    name: Build & Publish Docker images
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        service: [ {dir: Backend, tag: dhge-devops-backend}, {dir: Frontend, tag: dhge-devops-frontend}, {dir: SurveyEvaluation, tag: dhge-devops-surveyevaluation} ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.service.dir }}"
          push: true
          tags: diddyholz/${{ matrix.service.tag }}:latest
